export const countryLanguageMap: Record<string, string> = {
  AF: 'dari',
  AL: 'albanian',
  DZ: 'arabic',
  AO: 'portuguese',
  AR: 'spanish',
  AT: 'german',
  AU: 'english',
  AZ: 'azerbaijani',
  BA: 'bosnian',
  BE: 'dutch',
  BG: 'bulgarian',
  BH: 'arabic',
  BO: 'spanish',
  BR: 'portuguese',
  BY: 'belarusian',
  CA: 'english',
  CH: 'german',
  CL: 'spanish',
  CM: 'french',
  CN: 'chinese',
  CO: 'spanish',
  CU: 'spanish',
  CZ: 'czech',
  DE: 'german',
  DK: 'danish',
  DO: 'spanish',
  EC: 'spanish',
  EG: 'arabic',
  ES: 'spanish',
  ET: 'amharic',
  FI: 'finnish',
  FR: 'french',
  GA: 'french',
  GB: 'english',
  GE: 'georgian',
  GH: 'english',
  GR: 'greek',
  GT: 'spanish',
  HK: 'chinese',
  HR: 'croatian',
  HU: 'hungarian',
  ID: 'indonesian',
  IE: 'english',
  IL: 'hebrew',
  IN: 'hindi',
  IQ: 'arabic',
  IR: 'persian',
  IT: 'italian',
  JO: 'arabic',
  JP: 'japanese',
  KE: 'swahili',
  KH: 'khmer',
  KR: 'korean',
  KW: 'arabic',
  KZ: 'kazakh',
  LB: 'arabic',
  LK: 'sinhala',
  LY: 'arabic',
  MA: 'arabic',
  MX: 'spanish',
  MY: 'malay',
  NG: 'english',
  NL: 'dutch',
  NO: 'norwegian',
  NP: 'nepali',
  NZ: 'english',
  OM: 'arabic',
  PE: 'spanish',
  PH: 'filipino',
  PK: 'urdu',
  PL: 'polish',
  PT: 'portuguese',
  QA: 'arabic',
  RO: 'romanian',
  RS: 'serbian',
  RU: 'russian',
  SA: 'arabic',
  SD: 'arabic',
  SE: 'swedish',
  SG: 'english',
  SI: 'slovenian',
  SK: 'slovak',
  SN: 'french',
  SY: 'arabic',
  TH: 'thai',
  TN: 'arabic',
  TR: 'turkish',
  TW: 'chinese',
  TZ: 'swahili',
  UA: 'ukrainian',
  UG: 'english',
  US: 'english',
  UZ: 'uzbek',
  VE: 'spanish',
  VN: 'vietnamese',
  YE: 'arabic',
  ZA: 'zulu',
  ZW: 'shona',
};

export function getLanguageForCountry(countryCode: string): string {
  return countryLanguageMap[countryCode.toUpperCase()] ?? 'english';
}

export function getCountriesForLanguage(language: string): string[] {
  const lang = language.toLowerCase();
  return Object.entries(countryLanguageMap)
    .filter(([, l]) => l === lang)
    .map(([code]) => code);
}

export function isRTL(countryCode: string): boolean {
  const rtlLanguages = ['arabic', 'hebrew', 'persian', 'dari', 'urdu'];
  return rtlLanguages.includes(getLanguageForCountry(countryCode));
}
